name: Makefile CI

on:
  pull_request:
    branches: [ main ]

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Run markdownlint
      run: make markdownlint
